services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
